### ISSUE TITLE
Null reference exception thrown in MVC-hosted endpoint upon Bus.Start()

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.CastleWindsor#3] opened 2015-03-11 22:20 UTC
## Who's affected

- Anyone self hosting endpoint in ASP.NET MVC project using Windsor container and Azure ServiceBus transport

# Symptoms

`QueuesCreator` is not injected with an instance of `ICreateQueues` causing a null reference exception

Original post and [reproduction](https://groups.google.com/d/msg/particularsoftware/F0N2jatKMzc/Ta9WCKNpSvYJ) at [user group](https://groups.google.com/forum/#!topic/particularsoftware/F0N2jatKMzc)

**Comment by SzymonPobiega** [comment] 2015-03-12 05:01
It might be similar to this one: https://github.com/Particular/NServiceBus.Distributor.Msmq/issues/25. The issue there is that Autofac uses reverse order when resolving multiple implementations from the container.

**Comment by janovesk** [comment] 2015-03-13 15:19
Ok, so this took a while to debug.. :) The problem is in reproduction itself, not in NServiceBus. Castle Windsor installers run in a scope, and registrations in them are not available in the Windsor kernel before the installer finishes. So starting a bus INSIDE an installer is a bad idea, it leads to all kinds of weird side effects because things are semi-registered in the container. This issue is a good example. The solution is to not start a NServiceBus bus inside a Castle Windsor installer. Start if after all the installers have run.

**Closed by janovesk** 2015-03-13 15:19 UTC
Labels: Bug, Resolution: Won't Fix

**Comment by CRuppert** [comment] 2015-03-13 15:22
I would like to add that this is a change in functionality. Previous to NSB 5 It worked fine, I have working code to demonstrate that if you like. Is there some documentation to this effect?

**Comment by janovesk** [comment] 2015-03-13 15:35
Unfortunately we sometimes have to change internals in NServiceBus from one major version to another, like this. Starting a bus through a Windsor installer might have worked before, but that is more luck than intent from our part. If you still have a problem after starting the bus outside a installer, I'll be happy to look into it further.
